rvm:
  - 1.9.2
  - 1.9.3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "git clone git://github.com/n1k0/casperjs.git"
  - "cd casperjs"
  - "git checkout tags/0.6.5"
  - "sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs"

script: "bundle exec rake"

notifications:
  recipients:
    - joe@tribesports.com

branches:
  only:
    - master
