rvm:
  - 1.9.2
  - 1.9.3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: "bundle exec rake"

notifications:
  recipients:
    - joe@tribesports.com

branches:
  only:
    - master
